### ISSUE TITLE
Bug: This service does not work on Windows Server 2016 & 2019

### ISSUE THREAD

**Issue by R-Studio** [gfody/OnShutdown#1]
Hi @gfody 

We search exactly something like your service "OnShutdown", but unfortunately we are not able that your service works on Windows Server 2016 & 2019 VMs (Hyper-V).

I registered the Windows service like:
`New-Service OnShutDown -bin 'OnShutdown 4000 "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command {Get-process | out-file c:\temp\testfile.txt}"' -StartupType Automatic`

Do you have any idea why this is not working?

**Comment by gfody** [comment]
you may have to pass the full path to onshutdown.exe for New-Service -bin, you can check the SCM eventlog to be sure - it's probably saying path not found

**Comment by R-Studio** [comment]
@gfody thanks for your reply, I already tested this with the full path and unfortunately it isn't working. Here you can see the eventlog:
![image](https://user-images.githubusercontent.com/7498854/134630358-097761bd-76b0-4d59-9b2b-4fec60b634bf.png)

**Comment by gfody** [comment]
is there any message from starting the service? if you downloaded the .exe you may have to unblock it

**Comment by R-Studio** [comment]
> is there any message from starting the service? if you downloaded the .exe you may have to unblock it

Before I restart the VM, I checked that the service "OnShutDown" is running and the StartupType is automatic.
Here a snaphot of the logs:
![image](https://user-images.githubusercontent.com/7498854/134920539-b9bba06d-cb36-45fc-b389-7174432f14f3.png)

I don't think I have to "unblock" it, or what do you mean with that? I checked also the McAfee logs and McAfee don't block this service or executable.

**Comment by gfody** [comment]
by "unblock" I mean this option on the file properties for the exe (I'm not sure what this feature is called in windows, something to do with attachment manager - it's on by default)

![unblock](https://user-images.githubusercontent.com/1146032/135192969-f1e56c5f-9c1d-4f4b-9ce4-ba9f370ab319.png)

..however it looks like SCM is reporting that the service started and was running so I think you're past that.

Can you try testing with a shutdown instead of a reboot?  I'm not totally sure that SERVICE_CONTROL_PRESHUTDOWN is sent for reboots - at least I couldn't confirm with a simple google.

**Comment by R-Studio** [comment]
I tried with a normal shutdown but unfortunately it isn't working. 
_I am quite sure SERVICE_CONTROL_PRESHUTDOWN is should also working with a reboot._

**Comment by gfody** [comment]
@R-Studio have you tested the command? I get this error message:
```
'out-file' is not recognized as an internal or external command,
operable program or batch file.
```

I tested with a command like this and it works
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -command Get-process > c:\temp\testfile.txt
```

..fwiw, I'm using this in production to run powershell commands on shutdown and I do not put the full path to powershell, my command looks like this:
```
powershell -NonInteractive -Command \"some; commands\"
```
(note: you need to escape nested quotes when you register the service)

**Comment by R-Studio** [comment]
@gfody now I know my mistake and I am so dumb. I have misunderstood the instructions in your README.
I always tried with `{` and `}` after the parameter "-command" and that was the issue!

So instead of using:
`New-Service OnShutDown -bin 'C:\Temp\OnShutdown.exe 30000 "powershell -noninteractive -command {Get-process | out-file c:\temp\newesttest.txt}"' -StartupType Automatic`

I have to use it that way:
`New-Service OnShutDown -bin 'C:\Temp\OnShutdown.exe 30000 "powershell -noninteractive -command Get-process | out-file c:\temp\newesttest.txt"' -StartupType Automatic`

_PS: `Out-File` is a valid Cmdlet from the module "Microsoft.PowerShell.Utility"._

**Comment by gfody** [comment]
glad you got it working!  I found this relevant bit in the [doc for the -Command argument](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe?view=powershell-5.1#-command):

>The **Command** parameter only accepts a script block for execution when it can recognize the value passed to **Command** as a **ScriptBlock** type. This is _only_ possible when running `powershell.exe` from another PowerShell host. The **ScriptBlock** type may be contained in an existing variable, returned from an expression, or parsed by the PowerShell host as a literal script block enclosed in curly braces (`{}`), before being passed to `powershell.exe`.
>
>In `cmd.exe`, there is no such thing as a script block (or **ScriptBlock** type), so the value passed to **Command** will _always_ be a string. You can write a script block inside the string, but instead of being executed it will behave exactly as though you typed it at a typical PowerShell prompt, printing the contents of the script block back out to you.
>
>A string passed to **Command** is still executed as PowerShell code, so the script block curly braces are often not required in the first place when running from `cmd.exe`.

..I'll update the example accordingly
