### ISSUE TITLE
Question: Syntax for execution of a batch file with OnShutdown

### ISSUE THREAD

**Issue by Paulikid** [gfody/OnShutdown#2]
I have a batch file "C:\somebatch.bat". 

I didn´t manage to get the right syntax for registering the OnShutdown Service to execute this file on shutdown.

Could you please help me? 

Best regards,

P.

**Comment by gfody** [comment]
you probably want
```
PS> New-Service OnShutdown -bin 'OnShutdown 30000 "cmd.exe /c C:\somebatch.bat"'
```

**Comment by Paulikid** [comment]
This is exactly what I was looking for. 

Thank you very much for your help.
